### ISSUE TITLE
Figma - Protótipo 

### ISSUE THREAD

**Issue by CarolinaBarb** [FeudoAmareloGirassol/FeudoAmareloGirassol#34]
#  **FIGMA - PROTÓTIPO**

## Criar protótipo pro nosso site no figma.

# Tarefas
- [x] Criar Protótipo no Figma para o site.

**Comment by LucasLopesFrazao** [comment]
https://www.figma.com/file/QUPedLFXmgsv2GQBnBMIIW/ProjetoDS?node-id=0%3A1
